# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fdehan <fdehan@student.42luxembourg.lu>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/04/22 09:57:54 by fdehan            #+#    #+#              #
#    Updated: 2025/04/25 14:44:08 by fdehan           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

default:
	c++ -Werror -Wextra -Wall -g main_networking.cpp ../class/HttpBase.cpp ../class/HttpRequest.cpp \
	../class/EventMonitoring.cpp ../class/ClientData.cpp ../class/EventHandler.cpp ../class/HttpResponse.cpp
	