# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fdehan <fdehan@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/04/22 09:57:54 by fdehan            #+#    #+#              #
#    Updated: 2025/04/24 09:35:38 by fdehan           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

default:
	c++ -Werror -Wextra -Wall  main_networking.cpp ../class/HttpBase.cpp ../class/HttpRequest.cpp \
	../class/EventMonitoring.cpp ../class/ClientData.cpp ../class/BaseData.cpp
	